---
title: "Fig 7"
output: 
  html_document:
    df_print: paged
author: "Sangeev"
date: "`r Sys.time()`"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r}
# Prevent printing of warnings and such in the HTML
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = "center", eval = FALSE)
```

# Load packages
```{r}
library(tidyverse)
library(ggplot2)
```

#Fig7
```{r fig.width=7.5, fig.height=8.5}
#I have data for both stress and no stress. I am plotting only the stress. 

induced %>%
  filter(time != 0 & stress!="10mM_mg") %>%
  group_by(time, strain, Empty_vector) %>%
   summarise(mean.val = mean(OD), sem.val = sd(OD) / sqrt(n())) %>% 
  ungroup() %>%
  ggplot(aes(x = time, y = mean.val, color = Empty_vector)) +
 geom_point(size =0.5) +
  geom_line() +
  geom_errorbar(aes(ymin = mean.val - sem.val, ymax = mean.val + sem.val), 
                width = 0.4, size = 0.4, linetype = "solid", position = position_dodge(0.3)) +
  facet_wrap(~strain, ncol = 4) +
  scale_x_continuous() +
  scale_y_continuous(trans = "log2") +
  scale_color_manual(values = c("#de2d26", "#636363"), 
                   labels = c("Wild type/pSmall protein", "Wild type/pEmpty vector")) +
  labs(x = "Time (Hours)", y = expression(log[2]("OD"[600]) * ("a.u.")),
       color = NULL) +
  theme(text = element_text(size = 16, family = "Arial"),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(angle = 60, hjust = 1)) +
  annotation_logticks(sides = "l")+
  theme(legend.position = "bottom")

ggsave(plot = last_plot(),filename = "/data2/sangeev/paper1/updated_June24/figures/Fig7.png", width = 7.5, height = 8.5, units = "in", dpi = 600)
```
```

