---
title: "Fig S6"
output: 
  html_document:
    df_print: paged
author: "Sangeev"
date: "`r Sys.time()`"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r}
# Prevent printing of warnings and such in the HTML
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = "center", eval = FALSE)
```

# Load packages
```{r}
library(ggbeeswarm)
library(tidyverse)
library(ggplot2)
```

##FigS6A&B 
```{r}
envZ_ompFC <- read_csv("/data2/sangeev/paper1/updated_June24/other_analysis/dataframe/envZ_ompFC_reporter.csv")

envZ_ompFC  <- envZ_ompFC %>%
  mutate(strain = str_replace(strain, "empty", "Empty vector")) %>%
  mutate(strain = str_replace(strain, "yoaI", "YoaI"))

envZ_ompFC$stress <- factor(envZ_ompFC$stress, levels = c("no_mg", "10mM"))
envZ_ompFC$fluorescence <- factor(envZ_ompFC$fluorescence, levels = c("yfp", "cfp"))

mean_value_cfp<- envZ_ompFC %>%
  filter(fluorescence=="cfp" & stress=="10mM") %>%
  group_by(strain, stress) %>%
  summarise(mean.val=mean(intensity), .groups = 'drop') 

mean_value_yfp<- envZ_ompFC %>%
  filter(fluorescence=="yfp" & stress=="10mM") %>%
  group_by(strain, stress) %>%
  summarise(mean.val=mean(intensity), .groups = 'drop') 

color_yoaI2 <- c("YoaI" = "#de2d26", "Empty vector" = "#636363")
```

##FigS6A
```{r}
envZ_ompFC %>%
  filter(fluorescence=="cfp" & stress=="10mM") %>%
ggplot(., aes(x = strain, y = intensity, colour = strain, fill = "white")) +
geom_violin(fill="white", position = position_dodge(width = 0.9), adjust = 1) +
  geom_quasirandom(method='tukeyDense', alpha=0.1) +
  stat_summary(fun = mean, geom = "crossbar", size = 0.3, width= 0.3, color = "#2c7fb8") +
  labs(x = NULL, y = " PompC transcription CFP(a.u.)") +
  scale_fill_manual(values = "white") +  # Fill color for all boxes
  scale_color_manual(values = color_yoaI2) +  # Outline colors
  stat_compare_means(ref.group = "Empty vector", aes(label = ..p.signif..), symnum.args = symnum.args, method = "t.test") +
  theme(text = element_text(size = 15, family = "Arial"),
        panel.background = element_blank(),
        axis.line = element_line(color = "black")) +
  annotation_logticks(sides = "l") +
  theme(legend.position = "none") +
    theme(
  panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "gray80"), # Adjust major grid lines
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "gray90")) + 
  geom_text(data = mean_value_cfp, aes(x = strain, label = round(mean.val, 1)), y = 700, 
            vjust = 0, hjust = -0.2, color = "#2c7fb8", size = 3.5) 

ggsave(last_plot(), filename = "/data2/sangeev/paper1/updated_June24/figures/FigS6A.png", width = 3, height = 3.2, units = "in", dpi = 600) #without the mean value text
```


##FigS6B
```{r}
envZ_ompFC %>%
  filter(fluorescence=="yfp" & stress=="10mM") %>%
ggplot(., aes(x = strain, y = intensity, colour = strain, fill = "white")) +
geom_violin(fill="white", position = position_dodge(width = 0.9), adjust = 1) +
  geom_quasirandom(method='tukeyDense', alpha=0.1) +
  stat_summary(fun = mean, geom = "crossbar", size = 0.3, width= 0.3, color = "#2c7fb8") +
  labs(x = NULL, y = " PompF transcription YFP(a.u.)") +
  scale_fill_manual(values = "white") +  # Fill color for all boxes
  scale_color_manual(values = color_yoaI2) +  # Outline colors
  stat_compare_means(ref.group = "Empty vector", aes(label = ..p.signif..), symnum.args = symnum.args, method = "t.test") +
  theme(text = element_text(size = 15, family = "Arial"),
        panel.background = element_blank(),
        axis.line = element_line(color = "black")) +
  annotation_logticks(sides = "l") +
  theme(legend.position = "none") +
    theme(
  panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "gray80"), # Adjust major grid lines
  panel.grid.minor = element_line(size = 0.25, linetype = 'solid', colour = "gray90")) + 
  geom_text(data = mean_value_yfp, aes(x = strain, label = round(mean.val, 1)), y = 300, 
            vjust = 0, hjust = -0.2, color = "#2c7fb8", size = 3.5) 

ggsave(last_plot(), filename = "/data2/sangeev/paper1/updated_June24/figures/FigS6B.png", width = 3, height = 3.2, units = "in", dpi = 600) #without the mean value text
```

#Fig S6C
```{r fig.width=10, fig.height=5}

envZ_growth <- read_csv("~/Library/CloudStorage/Box-Box/github/Small-proteins-induced-under-low-magnesium-stress-in-E.coli/other_analysis/dataframe/YoaI_overexpression_envZ.csv")

envZ_growth$vector <- factor(envZ_growth$vector, levels = c("pYoaI", "pEmpty"))
envZ_growth %>%
  group_by(hour, vector) %>%
  summarise(mean.val = mean(OD), se.val = sd(OD) / sqrt(n())) %>%
  ungroup() %>%
  ggplot(aes(x = hour, y = mean.val, color = vector)) +
 geom_point(size = 1) +
  geom_line() +
  geom_errorbar(aes(ymin = mean.val - se.val, ymax = mean.val + se.val), 
                width = 0.4, size = 0.4, position = position_dodge(0.3)) +
  scale_x_continuous(breaks = seq(1, 20, 2)) +
  scale_y_continuous(trans = "log2") +
  scale_color_manual(values = c("#de2d26", "#636363"), 
                     labels = c("pYoaI", "pEmpty")) +
  labs(x = "Time (Hours)", y = expression(log[2]("OD"[600])),
       color = NULL) +
 theme(text = element_text(size = 17, family = "Arial"),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(angle = 60, hjust = 1)) +
  annotation_logticks(sides = "l")+
  theme(legend.position = "none")

ggsave(plot = last_plot(),filename = "~/Library/CloudStorage/Box-Box/github/Small-proteins-induced-under-low-magnesium-stress-in-E.coli/figures/FigS6C.png", width = 3, height = 2.2, units = "in", dpi = 600)
```
