---
title: "Fig S7C"
output: 
  html_document:
    df_print: paged
author: "Sangeev"
date: "`r Sys.time()`"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r}
# Prevent printing of warnings and such in the HTML
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = "center", eval = FALSE)
```

# Load packages
```{r}
library(tidyverse)
library(ggplot2)
```

#FigS7C
```{r}
yoaI_mut_growth <- read_csv("~/Library/CloudStorage/Box-Box/github/Small-proteins-induced-under-low-magnesium-stress-in-E.coli/other_analysis/dataframe/YoaI_overexpression_mutants.csv")

yoaI_mut_growth$vector <- factor(yoaI_mut_growth$vector, levels = c("pYoaI", "pYoaI_E31A", "pYoaI_E31Q", "pEmpty"))
yoaI_mut_growth %>%
  group_by(hour, vector) %>%
  summarise(mean.val = mean(OD), se.val = sd(OD) / sqrt(n())) %>%
  ungroup() %>%
  ggplot(aes(x = hour, y = mean.val, color = vector)) +
 geom_point(size = 1) +
  geom_line() +
  geom_errorbar(aes(ymin = mean.val - se.val, ymax = mean.val + se.val), 
                width = 0.4, size = 0.4, position = position_dodge(0.3)) +
  scale_x_continuous(breaks = seq(1, 20, 2)) +
  scale_y_continuous(trans = "log2") +
  scale_color_manual(values = c("#de2d26", "#31a354",  "#3182bd", "#636363"), 
                     labels = c("pYoaI_E31A", "pYoaI_E31Q", "pEmpty")) +
  labs(x = "Time (Hours)", y = expression(log[2]("OD"[600])),
       color = NULL) +
 theme(text = element_text(size = 17, family = "Arial"),
        panel.background = element_blank(),
        axis.line = element_line(color = "black"),
        axis.text.x = element_text(angle = 60, hjust = 1)) +
  annotation_logticks(sides = "l")+
  theme(legend.position = "none")

ggsave(plot = last_plot(),filename = "~/Library/CloudStorage/Box-Box/github/Small-proteins-induced-under-low-magnesium-stress-in-E.coli/figures/FigS7C.png", width = 3, height = 2.2, units = "in", dpi = 600)
```